# numpy ( Numerical python)
read --> https://docs.scipy.org/doc/numpy/user/quickstart.html

In [4]:
import numpy as np  # we can use numpy must be import 

In [5]:
import sys
import time
import matplotlib.pyplot as matpy

In [6]:
print('to cerate a array' )

a= np.array([1,2,3])                  # one dimensional array
print('one dim --->\n',a)
b= np.array([(1,2,3),(34,5,6)])     # two dimensional array [][]
print('two dim --->\n',b)
c= np.array([(1,2,3,4),(34,5,6,7),(1.9,3,'go','pi')])     # mult dimensional array [][][]
print('mult dim --->\n',c)

to cerate a array
one dim --->
 [1 2 3]
two dim --->
 [[ 1  2  3]
 [34  5  6]]
mult dim --->
 [['1' '2' '3' '4']
 ['34' '5' '6' '7']
 ['1.9' '3' 'go' 'pi']]


In [7]:
print('convert list into array')
#
d=[[1,2,3],[1,2,5],[6,7,8]]
D=np.array(d) #to convert list into array
print(D)



convert list into array
[[1 2 3]
 [1 2 5]
 [6 7 8]]


### comparsion of list and array

In [8]:
print('arrays are used less memorys')
#
r=range(10000)
print('memory of list used :',sys.getsizeof(5)*len(r)) # import sys

r=np.arange(10000)
print('memory of list used :',r.size*r.itemsize)
#
print('arrays are fast ie.,it take less time')
#
SIZE = 1000000
l1=range(SIZE)
l2=range(SIZE)
start = time.time()
result = [(x,y) for x,y in zip (l1,l2)]
print('time taken by list :',(time.time()-start)*1000,'msec') #import time

a1=np.arange(SIZE)
a2=np.arange(SIZE)
start = time.time()
result = a1+a2
print('time taken by array :',(time.time()-start)*1000,'msec')
#


arrays are used less memorys
memory of list used : 280000
memory of list used : 40000
arrays are fast ie.,it take less time
time taken by list : 256.0238838195801 msec
time taken by array : 66.56932830810547 msec


### numpy arras

In [9]:
print('to cerate a array' )
a= np.array([1,2,3])                  # one dimensional array
print('one dim --->\n',a)
b= np.array([(1,2,3,4),(34,5,6,5)])     # two dimensional array [][]
print('two dim --->\n',b)
c= np.array([(1,2,3,4),(3,5,6,7),(1,3,5,5)])   # mult dimensional array [][][]
print('mult dim  --->\n',c)

to cerate a array
one dim --->
 [1 2 3]
two dim --->
 [[ 1  2  3  4]
 [34  5  6  5]]
mult dim  --->
 [[1 2 3 4]
 [3 5 6 7]
 [1 3 5 5]]


### finding array porperties

In [12]:
print('finding array porperties:')
print('---------------------------')
print('array dimension-->a ',a.ndim)     # it returns the dimension of array
print('array b-->',b.ndim,'array c-->',c.ndim)
print('size of each element in array ',a.itemsize)  #it returns the each element size in the array
print('data type of elementin arrey ',a.dtype)#it return type of elements in the arrey
print('size of array',a.size)         # it returns size of array
print('shape of array',a.shape)     # it returns shape of array
print('shape of array',c.shape)     #o/p (no.of row, no.of colu)
#


finding array porperties:
---------------------------
array dimension-->a  1
array b--> 2 array c--> 2
size of each element in array  4
data type of elementin arrey  int32
size of array 3
shape of array (3,)
shape of array (3, 4)


### RESHAPE 
Returns an array containing the same data with a new shape.

In [17]:
print('reshape -->array.reshape(row,col)')
print('two dim --->\n',b)
#b=b.reshape(4,2)                it is covererts one shape into anther shape with in the array size
#print('reshape arrar \n',b)
B=np.reshape(b,(4,2))
print(B)

reshape -->array.reshape(row,col)
two dim --->
 [[ 1  2  3  4]
 [34  5  6  5]]
[[ 1  2]
 [ 3  4]
 [34  5]
 [ 6  5]]


### meshgrid

In [24]:
xx= np.array(range(0,10))
yy= np.array(range(0,6))
x,y = np.meshgrid(xx,yy)
print(x)
print(y)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5]]


### array math opration

In [44]:
print(' max,min & sum of numder in the array elements:')
print(a)
print('max number in the array : ',a.max())

print('sum of number in the array : ',a.sum())
print('returns max number index  in the array : ',a.argmax())
print('returns min number index in the array : ',a.argmin())
#
print('axis based opration in array :')               
print(c)
print('sum of each colum elements in array:\n',c.sum(axis=0)) #if axis=0 then sum of each colum elements in array will be return
print('sum of each row elements in array  :\n',c.sum(axis=1)) #if axis=1 then sum of each row elements in array will be return
print('sqrt of each element in array :\n',np.sqrt(c))
print('standard deviation of array :\n',np.std(c))

 max,min & sum of numder in the array elements:
[1 2 3]
max number in the array :  3
sum of number in the array :  6
returns max number index  in the array :  2
returns min number index in the array :  0
axis based opration in array :
[[1 2 3 4]
 [3 5 6 7]
 [1 3 5 5]]
sum of each colum elements in array:
 [ 5 10 14 16]
sum of each row elements in array  :
 [10 21 14]
sqrt of each element in array :
 [[1.         1.41421356 1.73205081 2.        ]
 [1.73205081 2.23606798 2.44948974 2.64575131]
 [1.         1.73205081 2.23606798 2.23606798]]
standard deviation of array :
 1.8314384146529925


In [ ]:
print("arrays +,-,*,/")

a=np.array([(1,2,3,4,),(4,5,6,7),(8,9,0,1)])
b=np.array([(1,3,5,6,),(4,5,6,7),(1,2,3,4,)])
print('add-->\n',a+b)
print('sub-->\n',a-b)
print('mul-->\n',a*b)
print('div-->\n',a/b)


In [ ]:
print('array a \n',a,'\n array b\n' ,b)
print('vertical stack of  array-->\n   ',np.vstack(a))# it  cerated  a vertical stack of array one are more array dependes on arg()
print('vertical stack of two array-->\n',np.vstack((a,b,)))  # (array 1,array 2)
print('array a \n',a,'\n array b\n',b)
print('horizontal stack of array-->\n'   ,np.hstack(a)) # it  cerated a horizontal stack of array one are more array dependes on arg()
print('horizontal stack of two array-->\n',np.hstack((a,b)))# (array 1,array 2)
print('flate')#  it  cerated vertical  into  horizontal  array and changes will not be feedback to the old array
print(' ravel of array-->\n',a.ravel())#  it  cerated vertical  into  horizontal  array and changes will be feedback to the old array


### equal deffernce numbers b/e two number

In [46]:
print('equal deffernce numbers b/e two numbers : np.linspace(start no,end no,no.of numbers b/e two numbers')
print(np.linspace(1,5,6)) #to get a equal deffernce numbers b/e two numbers
print(np.logspace(1,5,6))

equal deffernce numbers b/e two numbers : np.linspace(start no,end no,no.of numbers b/e two numbers
[1.  1.8 2.6 3.4 4.2 5. ]
[1.00000000e+01 6.30957344e+01 3.98107171e+02 2.51188643e+03
 1.58489319e+04 1.00000000e+05]


#### zeros or ones

In [ ]:
print(np.zeros(4)) #to print a no. zeros in n dim array
print(np.ones(5))  #to print a no. ones in n dim array
print(np.zeros((4,4))) #4 dim array


#### eye
Creates an identity matrix

In [48]:
I=np.identity(3,dtype=int)# creat squ mx
print(I)
ey=np.eye(4,3)#any dim
print(ey)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [51]:
ey=np.eye(4,3,k=2)#k=+ve for col k=-ve for row
print(ey)
print('------------------')
ey=np.eye(4,3,k=-2)#k=+ve for col k=-ve for row
print(ey)



[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [40]:
ey[0]=np.nan
ey[1]=np.inf#over flow
print(ey)
print(ey[0],ey[1])
np.isnan(ey)

[[nan nan nan nan]
 [inf inf inf inf]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[nan nan nan nan] [inf inf inf inf]


array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [41]:
print(np.where(np.isnan(ey)))
print(np.where(np.isinf(ey)))

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))
(array([1, 1, 1, 1], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [43]:
ey[np.where(np.isnan(ey))]=0.5
ey[np.where(np.isinf(ey))]=0.6
print(np.where(ey > 0.6))

(array([2, 3], dtype=int64), array([2, 3], dtype=int64))


In [ ]:
print('special functions')
#
print('to get a sin valve',np.sin(30))
print('to get a cos valve',np.cos(30))
print('to get a tan valve',np.tan(30))
print('to get a exponen valve',np.exp([1,3,4]))
print('to get a ln valve',np.log([1,3,4])) # nuturl log =>ln base 2
print('to get a ln valve',np.log10([1,3,4]))#log with base 10


In [ ]:
print('to get a sin,cos & tan etc.., plots')
#sin plot
x=np.arange(0,3*np.pi,0.1)
y=np.sin(x)                  #just replace sin with tan ,cat etc .,
matpy.plot(x,y)              #to plot x y plot & must be import matplotlib.pyplot
matpy.show()                 #to show a plot popup


In [ ]:
#cos plottial
x=np.arange(0,3*np.pi,0.1)
y=np.cos(x)
matpy.plot(x,y)
matpy.show()


In [ ]:
r=[1,1,2,3,4,5]
r1=np.array(r)
print(np.dtype(r1))
r1.astype(float)
print(r1)


## NumPy Indexing and Selection
 select elements or groups of elements from an array.

In [29]:
print('slicing ---> array[row:1-end row,col:1-end col]')
print("array c :",c)
print('slicing 1 :',c[0,2])   # index calling
print('slicing 2 :',c[0:,3]) # array[row:1-end row,indxe]
print('slicing 3 :',c[1:,1]) 
print('slicing 4 :',c[:,2])
print('slicing 5 :',c[0:2,3])



slicing ---> array[row:1-end row,col:1-end col]
array c : [[1 2 3 4]
 [3 5 6 7]
 [1 3 5 5]]
slicing 1 : 3
slicing 2 : [4 7 5]
slicing 3 : [5 3]
slicing 4 : [3 6 5]
slicing 5 : [4 7]


### Broadcasting
Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [13]:
#Setting a value with index range (Broadcasting)
arr = np.arange(0,11)
arr[0:5]=100
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [15]:
#Important notes on Slices
slice_of_arr = arr[0:6]

print(slice_of_arr)

[100 100 100 100 100   5]


In [18]:
#Change Slice
slice_of_arr[:]=99
#Show Slice again
print('slice_of_arr',slice_of_arr)
print('arr',arr)#Now note the changes also occur in our original array!

slice_of_arr [99 99 99 99 99 99]
arr [99 99 99 99 99 99  6  7  8  9 10]


### Indexing a 2D array (matrices)

In [20]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [21]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [24]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
print(arr_2d[1][0])

print(arr_2d[1,0])

20
20


In [27]:
# 2D array slicing
print(arr_2d)
#Shape (2,2) from top right corner

print(arr_2d[:2,1:])(r,c)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
[[10 15]
 [25 30]]


In [32]:
#Shape bottom row
print(arr_2d[2])
print(arr_2d[2,:])

[35 40 45]
[35 40 45]


###  Selection
selection based off of comparison operators.

In [35]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
print(arr>4)


[False False False False  True  True  True  True  True  True]


In [39]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

## Random
Numpy also has lots of ways to create random number arrays:

In [40]:
'''
https://docs.scipy.org/doc/numpy/reference/routines.random.html
'''
# numpy random sampling :
import numpy as np

#rand(d0, d1, …, dn)Random values in a given shape.(r,col)
print('rand\n',np.random.rand(3,2))

#randn(d0, d1, …, dn)Return a sample (or samples) from the “standard normal” distribution.
print('randn \n',np.random.randn(3,4))#(row,col)
      
#randint(low[, high, size, dtype])Return random integers from low (inclusive) to high (exclusive)
print('randint',np.random.randint(2,5,size=10))
print('randint', np.random.randint(2, size=10))
print('randint',np.random.randint(5, size=(2, 4)))#Generate a 2 x 4 array of ints between 0 and 4, inclusive:

#random_integers(low[, high, size]) Random integers of type np.int between low and high, inclusive.
print('random_integers',np.random.random_integers(10))
print('random_integers',np.random.random_integers(5,size=(3,2)))

#random_sample([size])Return random floats in the half-open interval [0.0, 1.0).
#random([size])Return random floats in the half-open interval [0.0, 1.0)
#ranf([size])Return random floats in the half-open interval [0.0, 1.0)
#sample([size])	Return random floats in the half-open interval [0.0, 1.0)
print('sample\n',np.random.random_sample((5,)))
print('sample \n',np.random.random_sample((5,6)))

#choice(a[, size, replace, p])Generates a random sample from a given 1-D array
print('choice',np.random.choice(5, 3)) #This is equivalent to np.random.randint(0,5,3)
print(np.random.choice(5, 3, p=[0.1, 0, 0.3, 0.6, 0]))#Generate a non-uniform random sample from np.arange(5) of size 3:
print(np.random.choice(5, 3, replace=False))#Generate a uniform random sample from np.arange(5) of size 3 without replacement:
#                                         #This is equivalent to np.random.permutation(np.arange(5))[:3]
print(np.random.choice(5, 3, replace=False, p=[0.1, 0, 0.3, 0.6, 0]))#Generate a non-uniform random sample from np.arange(5) of size 3 without replacement:

aa_milne_arr = ['pooh', 'rabbit', 'piglet', 'Christopher']
print(np.random.choice(aa_milne_arr, 5, p=[0.5, 0.1, 0.1, 0.3]))

#bytes(length)	Return random bytes.
print('bytes',np.random.bytes(5))


rand
 [[0.31924036 0.27837394]
 [0.46556315 0.69780669]
 [0.22054391 0.80767547]]
randn 
 [[ 1.05421588  0.70139149 -0.09718288 -1.20634476]
 [-1.44976293  0.09432883  0.86105679  2.58214679]
 [ 1.77549107  0.4863218  -0.25520098  0.4084793 ]]
randint [3 4 2 3 3 3 4 4 2 2]
randint [1 0 1 1 0 0 1 1 1 1]
randint [[3 2 0 3]
 [2 0 2 2]]
random_integers 6
random_integers [[5 1]
 [4 5]
 [1 3]]
sample
 [0.61281124 0.22307857 0.27802201 0.79456274 0.96335691]
sample 
 [[0.76642067 0.24298382 0.06648624 0.96752599 0.05930589 0.68917521]
 [0.03445415 0.79725102 0.25939352 0.55071285 0.78634381 0.74222594]
 [0.64352611 0.50809476 0.94646589 0.8043887  0.08984838 0.72802935]
 [0.84669595 0.36501857 0.52403637 0.1141231  0.2959268  0.19398957]
 [0.42941371 0.33189744 0.0174039  0.31699962 0.65902489 0.5638336 ]]
choice [0 4 4]
[2 3 3]
[1 4 2]
[3 2 0]
['pooh' 'piglet' 'Christopher' 'pooh' 'piglet']
bytes b'zh<)g'


c:\users\gopi\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:19: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
c:\users\gopi\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:20: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead


In [42]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'absolute', 'absolut